// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package logisticsbeta

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Purchaser             protoreflect.MessageDescriptor
	fd_Purchaser_purchaserid protoreflect.FieldDescriptor
	fd_Purchaser_active      protoreflect.FieldDescriptor
	fd_Purchaser_location    protoreflect.FieldDescriptor
	fd_Purchaser_walletId    protoreflect.FieldDescriptor
	fd_Purchaser_offchainId  protoreflect.FieldDescriptor
)

func init() {
	file_logisticsbeta_logisticsbeta_purchaser_proto_init()
	md_Purchaser = File_logisticsbeta_logisticsbeta_purchaser_proto.Messages().ByName("Purchaser")
	fd_Purchaser_purchaserid = md_Purchaser.Fields().ByName("purchaserid")
	fd_Purchaser_active = md_Purchaser.Fields().ByName("active")
	fd_Purchaser_location = md_Purchaser.Fields().ByName("location")
	fd_Purchaser_walletId = md_Purchaser.Fields().ByName("walletId")
	fd_Purchaser_offchainId = md_Purchaser.Fields().ByName("offchainId")
}

var _ protoreflect.Message = (*fastReflection_Purchaser)(nil)

type fastReflection_Purchaser Purchaser

func (x *Purchaser) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Purchaser)(x)
}

func (x *Purchaser) slowProtoReflect() protoreflect.Message {
	mi := &file_logisticsbeta_logisticsbeta_purchaser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Purchaser_messageType fastReflection_Purchaser_messageType
var _ protoreflect.MessageType = fastReflection_Purchaser_messageType{}

type fastReflection_Purchaser_messageType struct{}

func (x fastReflection_Purchaser_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Purchaser)(nil)
}
func (x fastReflection_Purchaser_messageType) New() protoreflect.Message {
	return new(fastReflection_Purchaser)
}
func (x fastReflection_Purchaser_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Purchaser
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Purchaser) Descriptor() protoreflect.MessageDescriptor {
	return md_Purchaser
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Purchaser) Type() protoreflect.MessageType {
	return _fastReflection_Purchaser_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Purchaser) New() protoreflect.Message {
	return new(fastReflection_Purchaser)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Purchaser) Interface() protoreflect.ProtoMessage {
	return (*Purchaser)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Purchaser) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Purchaserid != "" {
		value := protoreflect.ValueOfString(x.Purchaserid)
		if !f(fd_Purchaser_purchaserid, value) {
			return
		}
	}
	if x.Active != "" {
		value := protoreflect.ValueOfString(x.Active)
		if !f(fd_Purchaser_active, value) {
			return
		}
	}
	if x.Location != "" {
		value := protoreflect.ValueOfString(x.Location)
		if !f(fd_Purchaser_location, value) {
			return
		}
	}
	if x.WalletId != "" {
		value := protoreflect.ValueOfString(x.WalletId)
		if !f(fd_Purchaser_walletId, value) {
			return
		}
	}
	if x.OffchainId != "" {
		value := protoreflect.ValueOfString(x.OffchainId)
		if !f(fd_Purchaser_offchainId, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Purchaser) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "logisticsbeta.logisticsbeta.Purchaser.purchaserid":
		return x.Purchaserid != ""
	case "logisticsbeta.logisticsbeta.Purchaser.active":
		return x.Active != ""
	case "logisticsbeta.logisticsbeta.Purchaser.location":
		return x.Location != ""
	case "logisticsbeta.logisticsbeta.Purchaser.walletId":
		return x.WalletId != ""
	case "logisticsbeta.logisticsbeta.Purchaser.offchainId":
		return x.OffchainId != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: logisticsbeta.logisticsbeta.Purchaser"))
		}
		panic(fmt.Errorf("message logisticsbeta.logisticsbeta.Purchaser does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Purchaser) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "logisticsbeta.logisticsbeta.Purchaser.purchaserid":
		x.Purchaserid = ""
	case "logisticsbeta.logisticsbeta.Purchaser.active":
		x.Active = ""
	case "logisticsbeta.logisticsbeta.Purchaser.location":
		x.Location = ""
	case "logisticsbeta.logisticsbeta.Purchaser.walletId":
		x.WalletId = ""
	case "logisticsbeta.logisticsbeta.Purchaser.offchainId":
		x.OffchainId = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: logisticsbeta.logisticsbeta.Purchaser"))
		}
		panic(fmt.Errorf("message logisticsbeta.logisticsbeta.Purchaser does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Purchaser) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "logisticsbeta.logisticsbeta.Purchaser.purchaserid":
		value := x.Purchaserid
		return protoreflect.ValueOfString(value)
	case "logisticsbeta.logisticsbeta.Purchaser.active":
		value := x.Active
		return protoreflect.ValueOfString(value)
	case "logisticsbeta.logisticsbeta.Purchaser.location":
		value := x.Location
		return protoreflect.ValueOfString(value)
	case "logisticsbeta.logisticsbeta.Purchaser.walletId":
		value := x.WalletId
		return protoreflect.ValueOfString(value)
	case "logisticsbeta.logisticsbeta.Purchaser.offchainId":
		value := x.OffchainId
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: logisticsbeta.logisticsbeta.Purchaser"))
		}
		panic(fmt.Errorf("message logisticsbeta.logisticsbeta.Purchaser does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Purchaser) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "logisticsbeta.logisticsbeta.Purchaser.purchaserid":
		x.Purchaserid = value.Interface().(string)
	case "logisticsbeta.logisticsbeta.Purchaser.active":
		x.Active = value.Interface().(string)
	case "logisticsbeta.logisticsbeta.Purchaser.location":
		x.Location = value.Interface().(string)
	case "logisticsbeta.logisticsbeta.Purchaser.walletId":
		x.WalletId = value.Interface().(string)
	case "logisticsbeta.logisticsbeta.Purchaser.offchainId":
		x.OffchainId = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: logisticsbeta.logisticsbeta.Purchaser"))
		}
		panic(fmt.Errorf("message logisticsbeta.logisticsbeta.Purchaser does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Purchaser) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "logisticsbeta.logisticsbeta.Purchaser.purchaserid":
		panic(fmt.Errorf("field purchaserid of message logisticsbeta.logisticsbeta.Purchaser is not mutable"))
	case "logisticsbeta.logisticsbeta.Purchaser.active":
		panic(fmt.Errorf("field active of message logisticsbeta.logisticsbeta.Purchaser is not mutable"))
	case "logisticsbeta.logisticsbeta.Purchaser.location":
		panic(fmt.Errorf("field location of message logisticsbeta.logisticsbeta.Purchaser is not mutable"))
	case "logisticsbeta.logisticsbeta.Purchaser.walletId":
		panic(fmt.Errorf("field walletId of message logisticsbeta.logisticsbeta.Purchaser is not mutable"))
	case "logisticsbeta.logisticsbeta.Purchaser.offchainId":
		panic(fmt.Errorf("field offchainId of message logisticsbeta.logisticsbeta.Purchaser is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: logisticsbeta.logisticsbeta.Purchaser"))
		}
		panic(fmt.Errorf("message logisticsbeta.logisticsbeta.Purchaser does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Purchaser) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "logisticsbeta.logisticsbeta.Purchaser.purchaserid":
		return protoreflect.ValueOfString("")
	case "logisticsbeta.logisticsbeta.Purchaser.active":
		return protoreflect.ValueOfString("")
	case "logisticsbeta.logisticsbeta.Purchaser.location":
		return protoreflect.ValueOfString("")
	case "logisticsbeta.logisticsbeta.Purchaser.walletId":
		return protoreflect.ValueOfString("")
	case "logisticsbeta.logisticsbeta.Purchaser.offchainId":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: logisticsbeta.logisticsbeta.Purchaser"))
		}
		panic(fmt.Errorf("message logisticsbeta.logisticsbeta.Purchaser does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Purchaser) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in logisticsbeta.logisticsbeta.Purchaser", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Purchaser) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Purchaser) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Purchaser) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Purchaser) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Purchaser)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Purchaserid)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Active)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Location)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.WalletId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OffchainId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Purchaser)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.OffchainId) > 0 {
			i -= len(x.OffchainId)
			copy(dAtA[i:], x.OffchainId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OffchainId)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.WalletId) > 0 {
			i -= len(x.WalletId)
			copy(dAtA[i:], x.WalletId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.WalletId)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Location) > 0 {
			i -= len(x.Location)
			copy(dAtA[i:], x.Location)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Location)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Active) > 0 {
			i -= len(x.Active)
			copy(dAtA[i:], x.Active)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Active)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Purchaserid) > 0 {
			i -= len(x.Purchaserid)
			copy(dAtA[i:], x.Purchaserid)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Purchaserid)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Purchaser)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Purchaser: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Purchaser: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Purchaserid", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Purchaserid = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Active = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Location = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field WalletId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.WalletId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OffchainId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OffchainId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: logisticsbeta/logisticsbeta/purchaser.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Purchaser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Purchaserid string `protobuf:"bytes,1,opt,name=purchaserid,proto3" json:"purchaserid,omitempty"`
	Active      string `protobuf:"bytes,2,opt,name=active,proto3" json:"active,omitempty"`
	Location    string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	WalletId    string `protobuf:"bytes,4,opt,name=walletId,proto3" json:"walletId,omitempty"`
	OffchainId  string `protobuf:"bytes,5,opt,name=offchainId,proto3" json:"offchainId,omitempty"`
}

func (x *Purchaser) Reset() {
	*x = Purchaser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logisticsbeta_logisticsbeta_purchaser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Purchaser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchaser) ProtoMessage() {}

// Deprecated: Use Purchaser.ProtoReflect.Descriptor instead.
func (*Purchaser) Descriptor() ([]byte, []int) {
	return file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescGZIP(), []int{0}
}

func (x *Purchaser) GetPurchaserid() string {
	if x != nil {
		return x.Purchaserid
	}
	return ""
}

func (x *Purchaser) GetActive() string {
	if x != nil {
		return x.Active
	}
	return ""
}

func (x *Purchaser) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Purchaser) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Purchaser) GetOffchainId() string {
	if x != nil {
		return x.OffchainId
	}
	return ""
}

var File_logisticsbeta_logisticsbeta_purchaser_proto protoreflect.FileDescriptor

var file_logisticsbeta_logisticsbeta_purchaser_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x2f,
	0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x2f, 0x70, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x6c,
	0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x2e, 0x6c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x22, 0x9d, 0x01, 0x0a, 0x09, 0x50,
	0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x72, 0x63,
	0x68, 0x61, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x66,
	0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x42, 0xec, 0x01, 0x0a, 0x1f, 0x63,
	0x6f, 0x6d, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x42, 0x0e,
	0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x2c, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61,
	0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0xa2, 0x02,
	0x03, 0x4c, 0x4c, 0x58, 0xaa, 0x02, 0x1b, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x62, 0x65, 0x74, 0x61, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65,
	0x74, 0x61, 0xca, 0x02, 0x1b, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65,
	0x74, 0x61, 0x5c, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61,
	0xe2, 0x02, 0x27, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61,
	0x5c, 0x4c, 0x6f, 0x67, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x1c, 0x4c, 0x6f, 0x67,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x3a, 0x3a, 0x4c, 0x6f, 0x67, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x62, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescOnce sync.Once
	file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescData = file_logisticsbeta_logisticsbeta_purchaser_proto_rawDesc
)

func file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescGZIP() []byte {
	file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescOnce.Do(func() {
		file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescData = protoimpl.X.CompressGZIP(file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescData)
	})
	return file_logisticsbeta_logisticsbeta_purchaser_proto_rawDescData
}

var file_logisticsbeta_logisticsbeta_purchaser_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logisticsbeta_logisticsbeta_purchaser_proto_goTypes = []interface{}{
	(*Purchaser)(nil), // 0: logisticsbeta.logisticsbeta.Purchaser
}
var file_logisticsbeta_logisticsbeta_purchaser_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_logisticsbeta_logisticsbeta_purchaser_proto_init() }
func file_logisticsbeta_logisticsbeta_purchaser_proto_init() {
	if File_logisticsbeta_logisticsbeta_purchaser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logisticsbeta_logisticsbeta_purchaser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Purchaser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logisticsbeta_logisticsbeta_purchaser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logisticsbeta_logisticsbeta_purchaser_proto_goTypes,
		DependencyIndexes: file_logisticsbeta_logisticsbeta_purchaser_proto_depIdxs,
		MessageInfos:      file_logisticsbeta_logisticsbeta_purchaser_proto_msgTypes,
	}.Build()
	File_logisticsbeta_logisticsbeta_purchaser_proto = out.File
	file_logisticsbeta_logisticsbeta_purchaser_proto_rawDesc = nil
	file_logisticsbeta_logisticsbeta_purchaser_proto_goTypes = nil
	file_logisticsbeta_logisticsbeta_purchaser_proto_depIdxs = nil
}
