// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: logisticsbeta/logisticsbeta/system_info_4.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SystemInfo4 struct {
	NextTrade uint64 `protobuf:"varint,1,opt,name=nextTrade,proto3" json:"nextTrade,omitempty"`
}

func (m *SystemInfo4) Reset()         { *m = SystemInfo4{} }
func (m *SystemInfo4) String() string { return proto.CompactTextString(m) }
func (*SystemInfo4) ProtoMessage()    {}
func (*SystemInfo4) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b3c53977b70c9a6, []int{0}
}
func (m *SystemInfo4) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SystemInfo4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SystemInfo4.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SystemInfo4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemInfo4.Merge(m, src)
}
func (m *SystemInfo4) XXX_Size() int {
	return m.Size()
}
func (m *SystemInfo4) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemInfo4.DiscardUnknown(m)
}

var xxx_messageInfo_SystemInfo4 proto.InternalMessageInfo

func (m *SystemInfo4) GetNextTrade() uint64 {
	if m != nil {
		return m.NextTrade
	}
	return 0
}

func init() {
	proto.RegisterType((*SystemInfo4)(nil), "logisticsbeta.logisticsbeta.SystemInfo4")
}

func init() {
	proto.RegisterFile("logisticsbeta/logisticsbeta/system_info_4.proto", fileDescriptor_3b3c53977b70c9a6)
}

var fileDescriptor_3b3c53977b70c9a6 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcf, 0xc9, 0x4f, 0xcf,
	0x2c, 0x2e, 0xc9, 0x4c, 0x2e, 0x4e, 0x4a, 0x2d, 0x49, 0x44, 0xe3, 0x15, 0x57, 0x16, 0x97, 0xa4,
	0xe6, 0xc6, 0x67, 0xe6, 0xa5, 0xe5, 0xc7, 0x9b, 0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x49,
	0xa3, 0x28, 0xd1, 0x43, 0xe1, 0x29, 0x69, 0x73, 0x71, 0x07, 0x83, 0xf5, 0x78, 0xe6, 0xa5, 0xe5,
	0x9b, 0x08, 0xc9, 0x70, 0x71, 0xe6, 0xa5, 0x56, 0x94, 0x84, 0x14, 0x25, 0xa6, 0xa4, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x21, 0x04, 0x9c, 0x02, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48,
	0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96, 0x63, 0xb8, 0xf1,
	0x58, 0x8e, 0x21, 0xca, 0x3c, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f,
	0xa2, 0x22, 0xd8, 0x2f, 0x33, 0xa0, 0x22, 0x02, 0xe1, 0x34, 0x27, 0x90, 0xd3, 0x2a, 0xd0, 0x9c,
	0x5a, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x76, 0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0x43, 0x06, 0xdf, 0xd6, 0x00, 0x00, 0x00,
}

func (m *SystemInfo4) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SystemInfo4) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SystemInfo4) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextTrade != 0 {
		i = encodeVarintSystemInfo_4(dAtA, i, uint64(m.NextTrade))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSystemInfo_4(dAtA []byte, offset int, v uint64) int {
	offset -= sovSystemInfo_4(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SystemInfo4) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextTrade != 0 {
		n += 1 + sovSystemInfo_4(uint64(m.NextTrade))
	}
	return n
}

func sovSystemInfo_4(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSystemInfo_4(x uint64) (n int) {
	return sovSystemInfo_4(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SystemInfo4) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSystemInfo_4
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SystemInfo4: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SystemInfo4: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextTrade", wireType)
			}
			m.NextTrade = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSystemInfo_4
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextTrade |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSystemInfo_4(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSystemInfo_4
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSystemInfo_4(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSystemInfo_4
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSystemInfo_4
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSystemInfo_4
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSystemInfo_4
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSystemInfo_4
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSystemInfo_4
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSystemInfo_4        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSystemInfo_4          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSystemInfo_4 = fmt.Errorf("proto: unexpected end of group")
)
